#!/bin/bash

source /src/bin/helpers.bash

section "Activating virtual environment..."
cd /src
rm -rf env

install-python-packages
activate-virtualenv

if [ -n "${ARCANUS_PASSWORD}" ]; then
  section "Unlocking secrets..."
  install-gems
  arcanus unlock
fi
